# Generated by Django 5.2.5 on 2025-08-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'verbose_name': 'Tipo de Documento', 'verbose_name_plural': 'Tipos de Documentos'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
        migrations.AlterModelTable(
            name='documenttype',
            table='document_type',
        ),
        migrations.AlterModelTable(
            name='purchase',
            table='purchase',
        ),
    ]
